### ISSUE TITLE
[ADMIN][BLOG]: installer + configurer CKEditor 

### ISSUE THREAD

**Issue by fagathe-dev** [fagathe-dev/agathefrederick#38]
1. Installer le bundle avec composer  
```sh 
   composer require friendsofsymfony/ckeditor-bundle
```
2. Installer les assets
```sh
   php bin/console ckeditor:install
   php bin/console assets:install public
```
3. Configuration dans ``config/packages/fos_ck_editor.yaml``
```yaml
fos_ck_editor:
    configs:
        my_config:
            toolbar: [ ["Source", "-", "Save"], "/", ["Anchor"], "/", ["Maximize"] ]
            uiColor:                "#000000"
            filebrowserUploadRoute: "my_route"
            extraPlugins:           "wordcount"
```
5. Configuration dans ``config/packages/twig.yaml``
```yaml
twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
```
